"""empty message

Revision ID: 09add3669e5e
Revises: 2c34a45ccb14
Create Date: 2020-06-16 09:37:00.262621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09add3669e5e'
down_revision = '2c34a45ccb14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Location', sa.Column('notify_interval', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Location', 'notify_interval')
    # ### end Alembic commands ###
