"""empty message

Revision ID: 2c34a45ccb14
Revises: edd1ba1d9176
Create Date: 2020-06-16 09:12:13.911606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c34a45ccb14'
down_revision = 'edd1ba1d9176'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Location', sa.Column('last_notified', sa.DateTime(), nullable=True))
    op.add_column('Location', sa.Column('nofify_email', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Location', 'nofify_email')
    op.drop_column('Location', 'last_notified')
    # ### end Alembic commands ###
