"""empty message

Revision ID: 83bbcbcd3c72
Revises: 70370fe340cc
Create Date: 2020-06-10 09:24:44.127418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83bbcbcd3c72'
down_revision = '70370fe340cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('CounterStat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('hour', sa.Integer(), nullable=False),
    sa.Column('max_count', sa.Integer(), nullable=False),
    sa.Column('min_count', sa.Integer(), nullable=False),
    sa.Column('mvg_count', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['Location.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('CounterStat')
    # ### end Alembic commands ###
