"""empty message

Revision ID: 8815bf28063f
Revises: edd1ba1d9176
Create Date: 2020-06-16 11:23:04.413631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8815bf28063f'
down_revision = 'edd1ba1d9176'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Location', sa.Column('last_notified', sa.DateTime(), nullable=True))
    op.add_column('Location', sa.Column('notify_email_addresses', sa.Text(), server_default='', nullable=False))
    op.add_column('Location', sa.Column('notify_interval', sa.Integer(), server_default='3', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Location', 'notify_interval')
    op.drop_column('Location', 'notify_email_addresses')
    op.drop_column('Location', 'last_notified')
    # ### end Alembic commands ###
