"""empty message

Revision ID: b7871769520a
Revises: 09add3669e5e
Create Date: 2020-06-16 09:40:27.373716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7871769520a'
down_revision = '09add3669e5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Location', 'nofify_email',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('Location', 'notify_interval',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Location', 'notify_interval',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('Location', 'nofify_email',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
