"""empty message

Revision ID: bd3811283eb7
Revises: b13aca455908
Create Date: 2020-06-16 10:02:16.398241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd3811283eb7'
down_revision = 'b13aca455908'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Location', sa.Column('notify_email_addresses', sa.Text(), server_default='', nullable=False))
    op.drop_column('Location', 'nofify_email_addresses')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Location', sa.Column('nofify_email_addresses', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False))
    op.drop_column('Location', 'notify_email_addresses')
    # ### end Alembic commands ###
