"""location table

Revision ID: e1fc2043e735
Revises: f833d84d421f
Create Date: 2020-05-27 19:32:26.173405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1fc2043e735'
down_revision = 'f833d84d421f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('ok_limit', sa.Integer(), nullable=False),
    sa.Column('warning_limit', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('threshold')
    op.add_column('counter', sa.Column('location_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'counter', 'Location', ['location_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'counter', type_='foreignkey')
    op.drop_column('counter', 'location_id')
    op.create_table('threshold',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ok_limit', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('warning_limit', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='threshold_pkey')
    )
    op.drop_table('Location')
    # ### end Alembic commands ###
