"""empty message

Revision ID: edd1ba1d9176
Revises: 83bbcbcd3c72
Create Date: 2020-06-10 09:37:07.882710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edd1ba1d9176'
down_revision = '83bbcbcd3c72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('CounterStat', sa.Column('avg_count', sa.Integer(), nullable=False))
    op.drop_column('CounterStat', 'mvg_count')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('CounterStat', sa.Column('mvg_count', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('CounterStat', 'avg_count')
    # ### end Alembic commands ###
