"""added counter and threshold table

Revision ID: f833d84d421f
Revises: 3c18f5e9338a
Create Date: 2020-05-23 10:24:16.029835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f833d84d421f'
down_revision = '3c18f5e9338a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('counter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('threshold',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ok_limit', sa.Integer(), nullable=False),
    sa.Column('warning_limit', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('threshold')
    op.drop_table('counter')
    # ### end Alembic commands ###
